#!/usr/bin/perl

#
# NethServer
#
# Copyright (C) 2012 Nethesis srl
#

use strict;
use esmith::Build::CreateLinks  qw(:all);

event_actions('nethserver-php-update', qw(
       	      initialize-default-databases 00
));

templates2events('/etc/php.ini', qw(
        nethserver-php-update
        nethserver-php-save
));


